# Generated by Django 4.2.30 on 2026-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'user'], name='surveys_vot_poll_id_725dac_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll'], name='surveys_vot_poll_id_f5a9b9_idx'),
        ),
    ]
